package com.itantra.app.tts

import android.content.Context
import com.itantra.app.core.SupportedLanguage
import com.k2fsa.sherpa.onnx.OfflineTts
import com.k2fsa.sherpa.onnx.OfflineTtsConfig
import com.k2fsa.sherpa.onnx.OfflineTtsModelConfig
import com.k2fsa.sherpa.onnx.OfflineTtsVitsModelConfig
import com.k2fsa.sherpa.onnx.GenerationConfig

/**
 * Real offline Piper/VITS inference through sherpa-onnx.
 *
 * Model packs are generated by tools/fetch_models.py and live entirely in the APK
 * assets. No network request is made by this class at runtime.
 *
 * Expected asset layout:
 *   assets/models/tts/<language>/model.onnx
 *   assets/models/tts/<language>/tokens.txt
 *   assets/models/tts/<language>/espeak-ng-data/...
 */
class OnnxVitsTtsEngine(private val context: Context) : TtsEngine {

    private var tts: OfflineTts? = null

    override var outputSampleRate: Int = 22050
        private set

    override suspend fun loadModel(language: SupportedLanguage) {
        val modelDir = "models/tts/${language.bcp47}"
        val config = OfflineTtsConfig(
            model = com.k2fsa.sherpa.onnx.OfflineTtsModelConfig(
                vits = OfflineTtsVitsModelConfig(
                    model = "$modelDir/model.onnx",
                    tokens = "$modelDir/tokens.txt",
                    dataDir = "$modelDir/espeak-ng-data",
                ),
                numThreads = 1,
                provider = "cpu",
                debug = false,
            )
        )

        tts?.release()
        tts = OfflineTts(context.assets, config)
        outputSampleRate = tts?.sampleRate() ?: 22050
    }

    override suspend fun synthesize(text: String): TtsResult {
        val engine = tts ?: error("TTS model not loaded — call loadModel() first")
        val start = System.currentTimeMillis()
        val audio = engine.generateWithConfig(
            text = text,
            config = GenerationConfig(speed = 1.0f, silenceScale = 0.2f)
        )
        val elapsed = System.currentTimeMillis() - start
        val pcm16 = ShortArray(audio.samples.size) { i ->
            (audio.samples[i].coerceIn(-1f, 1f) * Short.MAX_VALUE).toInt().toShort()
        }
        return TtsResult(
            pcm16 = pcm16,
            sampleRate = audio.sampleRate,
            processingTimeMs = elapsed,
        )
    }

    override fun release() {
        tts?.release()
        tts = null
    }
}
